# Copyright (c) 2017-2021, Lawrence Livermore National Security, LLC and
# other Axom Project Developers. See the top-level LICENSE file for details.
#
# SPDX-License-Identifier: (BSD-3-Clause)

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PROJECT_ALLOC_NAME: ${CI_PROJECT_NAME}_ci_${CI_PIPELINE_ID}
  BUILD_ROOT: ${CI_PROJECT_DIR}

stages:
  - allocate
  - build
  - release

.src_workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH != "main" && $CI_COMMIT_BRANCH != "develop" && $BUILD_DEPS != "ON"' #run only if ...

.full_workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop" || $BUILD_DEPS == "ON"' #run only if ...

####
# Template
.src_build_script:
  script:
    #Use pre-existing allocation if any
    - JOBID=$(squeue -h --name=${PROJECT_ALLOC_NAME} --format=%A)
    - ASSIGN_ID=$(if [[ -n "${JOBID}" ]]; then echo "--jobid=${JOBID}"; fi)
   #BUILD + TEST
    - echo -e "section_start:$(date +%s):build_and_test\r\e[0K
      Build and test ${CI_PROJECT_NAME}"
    - ${ALLOC_COMMAND} scripts/llnl_scripts/build_src.py -v --host-config ${HOST_CONFIG} --extra-cmake-options -DENABLE_DOCS=OFF
    - echo -e "section_end:$(date +%s):build_and_test\r\e[0K"
  artifacts:
    paths:
      - _axom_build_and_test_*/output.log*.txt
      - _axom_build_and_test_*/build-*/output.log*.txt
    reports:
      junit: _axom_build_and_test_*/build-*/junit.xml

.full_build_script:
  script:
    - echo -e "section_start:$(date +%s):dependencies\r\e[0K
      Build dependencies and generate host-config file (uberenv)"
    - ${ALLOC_COMMAND} scripts/llnl_scripts/build_tpls.py -v --spec="${SPEC} ${EXTRA_SPEC}" --directory=${CI_BUILDS_DIR}/axom_tpls/${CI_RUNNER_ID} --mirror=${CI_BUILDS_DIR}/axom_tpls
    - echo -e "section_end:$(date +%s):dependencies\r\e[0K"
  artifacts:
    paths:
      - _axom_build_and_test_*/output.log*.txt
      - _axom_build_and_test_*/build-*/output.log*.txt
    reports:
      junit: _axom_build_and_test_*/build-*/junit.xml

# This is where jobs are included
include:
  - local: .gitlab/build_ruby.yml
  - local: .gitlab/build_lassen.yml

