# Copyright (c) 2017-2021, Lawrence Livermore National Security, LLC and
# other Axom Project Developers. See the top-level LICENSE file for details.
#
# SPDX-License-Identifier: (BSD-3-Clause)

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PROJECT_ALLOC_NAME: ${CI_PROJECT_NAME}_ci_${CI_PIPELINE_ID}
  BUILD_ROOT: ${CI_PROJECT_DIR}

stages:
  - allocate
  - build
  - release

.always_rule:
  rules:
    - when: always

.manual_rule:
  rules:
    - when: manual

####
# Template
.src_build_script:
  script:
    # Use pre-existing allocation if any
    - JOBID=$(if [[ "$SYS_TYPE" == "toss_3_x86_64_ib" ]]; then squeue -h --name=${PROJECT_ALLOC_NAME} --format=%A; fi)
    - ASSIGN_ID=$(if [[ -n "${JOBID}" ]]; then echo "--jobid=${JOBID}"; fi)
    # BUILD + TEST
    - echo -e "section_start:$(date +%s):src_build_and_test\r\e[0K
      Source Build and Test ${CI_PROJECT_NAME}"
    - ${ALLOC_COMMAND} scripts/llnl_scripts/build_src.py -v --host-config ${HOST_CONFIG} --extra-cmake-options -DENABLE_DOCS=OFF
    - echo -e "section_end:$(date +%s):src_build_and_test\r\e[0K"
  artifacts:
    paths:
      - _axom_build_and_test_*/output.log*.txt
      - _axom_build_and_test_*/build-*/output.log*.txt
    reports:
      junit: _axom_build_and_test_*/build-*/junit.xml

.full_build_script:
  script:
    - echo -e "section_start:$(date +%s):full_build_and_test\r\e[0K
      Full Build and Test ${CI_PROJECT_NAME}"
    - ${ALLOC_COMMAND} scripts/llnl_scripts/build_tpls.py -v --spec="${SPEC} ${EXTRA_SPEC}" --directory=./${CI_JOB_NAME}
    - echo -e "section_end:$(date +%s):full_build_and_test\r\e[0K"
  artifacts:
    paths:
      - ./${CI_JOB_NAME}/${SYS_TYPE}/*/_axom_build_and_test_*/output.log*.txt
      - ./${CI_JOB_NAME}/${SYS_TYPE}/*/_axom_build_and_test_*/build-*/output.log*.txt
    reports:
      junit: ./${CI_JOB_NAME}/${SYS_TYPE}/*/_axom_build_and_test_*/build-*/junit.xml

# This is where jobs are included
include:
  - local: .gitlab/build_ruby.yml
  - local: .gitlab/build_lassen.yml
